Repository marmelab/react-admin, pull requests merged in 2020-09, with the labels that each got.

#5223 Fix Firefox support in end-to-end tests
  cypress/cypress.json
  cypress/package.json
  yarn.lock
Labels: RFR

#5227 Fix vulnerability in simple example due to serve package
  examples/simple/package.json
  yarn.lock
Labels: RFR

#5230 fix: warning proptypes in ListToolBar component
  packages/ra-ui-materialui/src/list/ListToolbar.tsx
Labels: RFR

#5224 simpleRestProvider: using a custom http header to count items in a collection
  packages/ra-data-simple-rest/README.md
  packages/ra-data-simple-rest/src/index.spec.ts
  packages/ra-data-simple-rest/src/index.ts
Labels: RFR, enhancement

#5222 Support function for initialValues
  packages/ra-core/src/form/getFormInitialValues.spec.ts
  packages/ra-core/src/form/getFormInitialValues.ts
Labels: RFR

#5234 Fix filter margin-top that create an invisible overlay
  packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
  packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
Labels: RFR

#5236 Fix the welcome banner style of the demo
  examples/demo/src/dashboard/Welcome.tsx
  examples/demo/src/dashboard/welcome_bg.png
  examples/demo/src/i18n/en.ts
  examples/demo/src/i18n/fr.ts
Labels: RFR

#5254 Fix useLogoutIfAccessDenied hook syntax error
  packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
Labels: RFR

#5245 Change the Catalan translation repository
  docs/Translation.md
Labels: RFR, documentation

#5257 [BC Break] Rename duplicate types to allow type emission from react-admin
  packages/ra-core/src/actions/accumulateActions.ts
  packages/ra-core/src/actions/dataActions/crudGetAll.ts
  packages/ra-core/src/actions/dataActions/crudGetList.ts
  packages/ra-core/src/actions/dataActions/crudGetManyReference.ts
  packages/ra-core/src/actions/dataActions/crudGetMatching.ts
  packages/ra-core/src/actions/notificationActions.ts
  packages/ra-core/src/controller/field/ReferenceArrayFieldController.tsx
  packages/ra-core/src/controller/field/ReferenceManyFieldController.tsx
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
  packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx
  packages/ra-core/src/controller/input/ReferenceInputController.tsx
  packages/ra-core/src/controller/input/useGetMatchingReferences.ts
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-core/src/controller/input/useReferenceInputController.ts
  packages/ra-core/src/controller/useFilterState.ts
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/controller/useListParams.ts
  packages/ra-core/src/controller/usePaginationState.ts
  packages/ra-core/src/controller/useSortState.ts
  packages/ra-core/src/dataProvider/useGetList.ts
  packages/ra-core/src/dataProvider/useGetManyReference.ts
  packages/ra-core/src/dataProvider/useGetMatching.ts
  packages/ra-core/src/reducer/admin/notifications.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/auth/Login.tsx
  packages/ra-ui-materialui/src/button/ExportButton.tsx
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
  packages/ra-ui-materialui/src/input/ReferenceInput.tsx
  packages/ra-ui-materialui/src/layout/Layout.tsx
  packages/ra-ui-materialui/src/list/ListActions.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
  packages/ra-ui-materialui/src/types.ts
  packages/ra-ui-materialui/tsconfig.json
Labels: RFR

#5261 Update Tutorial Links
  docs/AdvancedTutorials.md
Labels: RFR

#5264 Fix Datagrid Header Cells Remove Border Radius
  packages/ra-ui-materialui/src/list/datagrid/useDatagridStyles.tsx
Labels: RFR

#5260 Add onSuccess Callback Infos about undoable prop
  docs/CreateEdit.md
Labels: RFR

#5263 Fix unexpected List Page Change
  examples/demo/src/reviews/BulkAcceptButton.tsx
  examples/demo/src/reviews/BulkRejectButton.tsx
  packages/ra-core/src/controller/useListController.ts
Labels: RFR

#5277 [Doc] Fix docs links
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Custom.md
  CHANGELOG.md
  README.md
  docs/Admin.md
  docs/Authentication.md
  docs/CustomApp.md
  docs/DataProviders.md
  docs/Ecosystem.md
  docs/Fields.md
  docs/Inputs.md
  docs/Readme.md
  docs/Translation.md
  docs/Tutorial.md
  examples/data-generator/README.md
  examples/demo/README.md
  packages/ra-core/README.md
  packages/ra-data-fakerest/README.md
  packages/ra-data-graphql-simple/README.md
  packages/ra-data-graphql/README.md
  packages/ra-data-json-server/README.md
  packages/ra-data-simple-rest/README.md
  packages/ra-i18n-polyglot/README.md
  packages/ra-input-rich-text/README.md
  packages/ra-language-english/README.md
  packages/ra-language-french/README.md
  packages/ra-ui-materialui/README.md
  packages/react-admin/README.md
Labels: RFR, documentation

#5285 Improve the documentation of the SaveButton when customizing the Toolbar
  docs/CreateEdit.md
Labels: RFR

#5284 Add ra-enterprise packages to Ecosystem documentation
  docs/Ecosystem.md
  docs/Fields.md
  docs/Inputs.md
  docs/List.md
  docs/css/style-v5.css
  docs/img/premium.svg
Labels: RFR

#5300 Fix warning when passing FieldProps to Input components
  packages/ra-ui-materialui/src/input/sanitizeRestProps.ts
Labels: RFR

#5298 More TS fixes
  examples/demo/package.json
  examples/simple/package.json
  examples/tutorial/package.json
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-core/src/controller/useShowController.ts
  packages/ra-core/src/dataProvider/index.ts
  packages/ra-core/src/types.ts
  packages/ra-data-fakerest/package.json
  packages/ra-data-graphql-simple/package.json
  packages/ra-data-graphql/package.json
  packages/ra-data-simple-rest/package.json
  packages/ra-input-rich-text/package.json
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/button/Button.tsx
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/index.ts
  packages/ra-ui-materialui/src/detail/Show.tsx
  packages/ra-ui-materialui/src/detail/ShowActions.tsx
  packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx
  packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx
  packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.tsx
  packages/ra-ui-materialui/src/detail/index.ts
  packages/ra-ui-materialui/src/form/SimpleForm.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.tsx
  packages/ra-ui-materialui/src/form/index.tsx
  packages/ra-ui-materialui/src/input/Labeled.tsx
  packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
  packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
  packages/ra-ui-materialui/src/layout/Sidebar.tsx
  packages/ra-ui-materialui/src/layout/index.ts
  packages/ra-ui-materialui/src/list/SimpleList.tsx
  packages/ra-ui-materialui/src/list/datagrid/ExpandRowButton.tsx
  packages/ra-ui-materialui/src/types.ts
Labels: RFR

#5313 More TS fixes
  packages/ra-core/src/controller/useCreateController.ts
  packages/ra-core/src/controller/useEditController.ts
  packages/ra-core/src/controller/useShowController.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/detail/Create.tsx
  packages/ra-ui-materialui/src/detail/Edit.tsx
  packages/ra-ui-materialui/src/detail/Show.tsx
  packages/ra-ui-materialui/src/layout/index.ts
Labels: RFR

#5318 More TypeScript Fixes
  packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
  packages/ra-core/src/export/fetchRelatedRecords.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/list/ListActions.tsx
  packages/ra-ui-materialui/src/list/index.ts
Labels: RFR

#5327 Fix the last testimonial which is not reachable
  index.html
Labels: RFR, documentation
