Repository marmelab/react-admin, pull requests merged in 2020-07, with the labels that each got.

#4997 Update ecommerce demo product references
  examples/data-generator/src/products.js
  examples/demo/src/products/ProductList.tsx
Labels: RFR

#5004 Document dynamic resources
  docs/Admin.md
Labels: RFR, documentation

#5013 Fix typo
  packages/ra-data-simple-rest/README.md
Labels: RFR

#5015 Remove ra-data-graphcool dataProvider
  Makefile
  cypress/support/CreatePage.js
  docs/DataProviders.md
  examples/simple/src/Dashboard.js
  examples/simple/src/index.js
  examples/simple/src/posts/PostCreate.js
  packages/ra-data-graphcool/README.md
  packages/ra-data-graphcool/package.json
  packages/ra-data-graphcool/src/buildGqlQuery.js
  packages/ra-data-graphcool/src/buildGqlQuery.test.js
  packages/ra-data-graphcool/src/buildQuery.js
  packages/ra-data-graphcool/src/buildQuery.test.js
  packages/ra-data-graphcool/src/buildVariables.js
  packages/ra-data-graphcool/src/buildVariables.test.js
  packages/ra-data-graphcool/src/getFinalType.js
  packages/ra-data-graphcool/src/getFinalType.test.js
  packages/ra-data-graphcool/src/getResponseParser.js
  packages/ra-data-graphcool/src/getResponseParser.test.js
  packages/ra-data-graphcool/src/index.js
  packages/ra-data-graphcool/src/isList.js
  packages/ra-data-graphcool/src/isList.test.js
  packages/ra-data-graphcool/src/isRequired.js
  packages/ra-data-graphcool/src/isRequired.test.js
  packages/ra-data-graphcool/tsconfig.json
  packages/ra-data-graphql/README.md
  tsconfig.json
Labels: RFR

#5033 Fix documentation : Remove unused import of EditButton
  docs/Show.md
Labels: RFR, documentation

#5051 Replace recompose's shallowEqual with react-redux's shallowEqual.
  packages/ra-core/src/util/removeEmpty.ts
  packages/ra-ui-materialui/src/input/FileInput.tsx
Labels: RFR

#5042 [RFR] Fix ESLint @material-ui/core rule configuration
  .eslintrc
  examples/demo/src/dashboard/CardWithIcon.tsx
  examples/demo/src/dashboard/PendingReviews.tsx
  packages/ra-ui-materialui/src/field/BooleanField.tsx
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/list/Empty.tsx
  packages/ra-ui-materialui/src/list/ListToolbar.tsx
  packages/ra-ui-materialui/src/list/SimpleList.tsx
  packages/ra-ui-materialui/src/list/useDatagridStyles.tsx
Labels: RFR

#5053 Fix - Sanitize the pagination prop passed to the SelectInput
  packages/ra-ui-materialui/src/input/SelectInput.tsx
Labels: RFR

#5055 Fix eslint version
  package.json
  yarn.lock
Labels: RFR

#5061 Fix docs title
  docs/Admin.md
Labels: RFR

#5065 Prepare the integration of the Enterprise Edition Page
  assets/generate-copyright-date.js
  assets/styles.css
  index.html
  thank-you/index.html
Labels: RFR, documentation

#5060 Added `ra-postgraphile` for `PostGraphile` as Data Provider
  docs/DataProviders.md
Labels: RFR

#5068 Fix CORS issue in simple example codesandbox
  examples/simple/webpack.config.js
Labels: RFR, bug

#5073 Set notification over confirms dialog, not under
  packages/ra-ui-materialui/src/layout/Layout.js
Labels: RFR

#5002 Add ability to make the <SaveButton> not disabled by default
  docs/CreateEdit.md
  packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
  packages/ra-ui-materialui/src/button/SaveButton.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.js
  packages/ra-ui-materialui/src/form/TabbedForm.js
  packages/ra-ui-materialui/src/form/Toolbar.js
Labels: RFR, breaking change

#5075 Fixes in docs
  docs/Admin.md
  docs/Caching.md
  docs/CreateEdit.md
  docs/DataProviders.md
  docs/List.md
  docs/Theming.md
  docs/Translation.md
Labels: RFR, documentation

#5084 Fix typo
  examples/simple/src/authProvider.js
Labels: documentation

#5083 ra-ui-materialui/src/button/SaveButton - Small Typo in comment line
  packages/ra-ui-materialui/src/button/SaveButton.tsx
Labels: documentation

#5080 Typo FormDataConsumer.tsx
  packages/ra-core/src/form/FormDataConsumer.tsx
Labels: documentation

#4894 Fix pagination on bulk delete
  packages/ra-core/src/controller/useListController.spec.tsx
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/controller/useListParams.spec.ts
  packages/ra-core/src/controller/useListParams.ts
  packages/ra-ui-materialui/src/field/ArrayField.tsx
  packages/ra-ui-materialui/src/list/Pagination.spec.js
  packages/ra-ui-materialui/src/list/Pagination.tsx
Labels: RFR

#4818 enhancement: allow custom add and remove buttons in SimpleFormIterator
  docs/Inputs.md
  packages/ra-ui-materialui/src/form/SimpleFormIterator.js
  packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.js
Labels: enhancement

#5087 Remove recompose dependency from ra-core and demo projects.
  examples/demo/package.json
  packages/ra-core/package.json
  packages/ra-core/src/util/removeEmpty.ts
Labels: RFR

#5092 Fix Default Color in Layout
  packages/ra-ui-materialui/src/layout/Layout.js
Labels: RFR, bug

#5088 Remove recompose
  CHANGELOG.md
  README.md
  UPGRADE.md
  docs/CustomApp.md
  examples/demo/package.json
  package.json
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/input/FileInput.tsx
  packages/ra-ui-materialui/src/layout/Layout.js
  packages/react-admin/README.md
  yarn.lock
Labels: RFR, breaking change

#5095 Fix a typo in documentation about the <SimpleFormIterator>
  docs/Inputs.md
Labels: RFR, documentation
