Repository marmelab/react-admin, pull requests merged in 2020-11, with the labels that each got.

#5468 [Doc] Fix typo in tutorial
  docs/Tutorial.md
Labels: RFR, documentation

#5465 [Demo] Fix chart gets empty at the end of the month
  examples/demo/src/dashboard/Dashboard.tsx
  examples/demo/src/dashboard/NewCustomers.tsx
  examples/demo/src/dashboard/OrderChart.tsx
Labels: RFR

#5472 [Demo] use stepper for customer actions
  examples/demo/src/visitors/Aside.tsx
Labels: RFR

#5473 Fix layout component type
  examples/demo/src/layout/Layout.tsx
  examples/demo/src/layout/Menu.tsx
  examples/demo/src/layout/themes.ts
  packages/ra-core/src/core/CoreAdminRouter.tsx
  packages/ra-core/src/core/CoreAdminUI.tsx
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/layout/Layout.tsx
  packages/ra-ui-materialui/src/layout/Menu.tsx
  packages/ra-ui-materialui/src/layout/index.ts
Labels: RFR

#5456 Introduce Resource Context
  packages/ra-core/src/actions/resourcesActions.ts
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
  packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
  packages/ra-core/src/controller/details/useCreateController.ts
  packages/ra-core/src/controller/details/useEditController.ts
  packages/ra-core/src/controller/details/useShowController.ts
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
  packages/ra-core/src/controller/input/useGetMatchingReferences.ts
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-core/src/controller/input/useReferenceInputController.ts
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/core/Resource.tsx
  packages/ra-core/src/core/ResourceContext.ts
  packages/ra-core/src/core/ResourceContextProvider.tsx
  packages/ra-core/src/core/index.ts
  packages/ra-core/src/core/useResourceContext.ts
  packages/ra-core/src/core/useResourceDefinition.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
  packages/ra-ui-materialui/src/button/ExportButton.tsx
  packages/ra-ui-materialui/src/detail/CreateActions.js
  packages/ra-ui-materialui/src/detail/EditActions.tsx
  packages/ra-ui-materialui/src/detail/ShowActions.tsx
  packages/ra-ui-materialui/src/detail/ShowView.tsx
  packages/ra-ui-materialui/src/list/BulkDeleteAction.tsx
  packages/ra-ui-materialui/src/list/Empty.tsx
  packages/ra-ui-materialui/src/list/ListActions.tsx
  packages/ra-ui-materialui/src/list/ListGuesser.tsx
  packages/ra-ui-materialui/src/list/SingleFieldList.tsx
  packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
  packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
Labels: RFR

#5481 Fix error when using withDataProvider without options argument
  packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
  packages/ra-core/src/dataProvider/withDataProvider.tsx
Labels: RFR

#5485 Add ability to infer field type from data
  packages/ra-core/src/inference/index.ts
  packages/ra-core/src/inference/inferTypeFromValues.ts
  packages/ra-core/src/inference/inferTypesFromValues.spec.ts
Labels: RFR

#5488 Fix EmailField with target prop fails TypeScript compilation
  packages/ra-ui-materialui/src/field/EmailField.tsx
  packages/ra-ui-materialui/src/field/UrlField.tsx
Labels: RFR

#5487 Fix crash when navigating away during undo period
  packages/ra-core/src/dataProvider/useDataProvider.ts
Labels: RFR

#5489 Update the ResourceContext to store a scalar instead of an object
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
  packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
  packages/ra-core/src/controller/details/useCreateController.ts
  packages/ra-core/src/controller/details/useEditController.ts
  packages/ra-core/src/controller/details/useShowController.ts
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
  packages/ra-core/src/controller/input/useGetMatchingReferences.ts
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-core/src/controller/input/useReferenceInputController.ts
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/core/Resource.tsx
  packages/ra-core/src/core/ResourceContext.ts
  packages/ra-core/src/core/useResourceContext.ts
  packages/ra-core/src/core/useResourceDefinition.ts
  packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
  packages/ra-ui-materialui/src/button/ExportButton.tsx
  packages/ra-ui-materialui/src/detail/ShowView.tsx
  packages/ra-ui-materialui/src/list/BulkDeleteAction.tsx
  packages/ra-ui-materialui/src/list/Empty.tsx
  packages/ra-ui-materialui/src/list/ListActions.tsx
  packages/ra-ui-materialui/src/list/ListGuesser.tsx
  packages/ra-ui-materialui/src/list/SingleFieldList.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
  packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
Labels: RFR

#5493 [Doc] Improve Auth Provider chapter
  docs/Admin.md
  docs/Authentication.md
  docs/Authorization.md
  docs/Ecosystem.md
  docs/Reference.md
  docs/UnitTesting.md
  docs/navigation.html
Labels: RFR

#5502 Change RecordContext in Reference elements
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
  packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
  packages/ra-ui-materialui/src/input/ReferenceInput.tsx
  packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Labels: RFR

#5504 [Doc] Fix search input is not visible enough
  docs/_layouts/default.html
  docs/css/style-v9.css
Labels: RFR

#5508 Migrate CI to Github Actions
  .github/workflows/test.yml
  .travis.yml
  Makefile
  packages/ra-core/src/auth/Authenticated.spec.tsx
  packages/ra-core/src/controller/details/useEditController.spec.tsx
  packages/ra-core/src/controller/useListContext.spec.tsx
  packages/ra-core/src/core/CoreAdminRouter.spec.tsx
  packages/ra-core/src/core/Resource.spec.tsx
  packages/ra-core/src/core/useResourceContext.ts
  packages/ra-core/src/form/ValidationError.spec.tsx
  packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
  packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
  packages/ra-ui-materialui/src/form/FormTab.spec.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
  packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
  packages/ra-ui-materialui/src/input/InputHelperText.spec.tsx
  packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.spec.tsx
Labels: WIP

#5524 Fix useDataProvider throws options is undefined error when called without arguments
  packages/ra-core/src/dataProvider/getDataProviderCallArguments.ts
  packages/ra-core/src/dataProvider/useDataProvider.spec.js
Labels: RFR

#5523 Fix setImmediate is not defined error
  packages/ra-core/src/dataProvider/useQueryWithStore.ts
Labels: RFR

#5453 Use React 17 in examples to make sure react-admin works with this version
  cypress/package.json
  cypress/plugins/index.js
  cypress/support/index.js
  examples/demo/package.json
  examples/demo/tsconfig.json
  examples/simple/package.json
  examples/tutorial/package.json
  package.json
  packages/ra-core/package.json
  packages/ra-core/src/core/Resource.spec.tsx
  packages/ra-core/src/form/useInput.spec.tsx
  packages/ra-input-rich-text/package.json
  packages/ra-input-rich-text/src/index.tsx
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/BooleanInput.spec.tsx
  packages/ra-ui-materialui/src/input/DateInput.spec.tsx
  packages/ra-ui-materialui/src/input/FileInputPreview.spec.tsx
  packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
  packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
  packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
  packages/ra-ui-materialui/src/input/TextInput.spec.tsx
  packages/react-admin/package.json
  tsconfig.json
  yarn.lock
Labels: RFR

#5532 Fix Views Types
  examples/demo/src/visitors/VisitorList.tsx
  packages/ra-ui-materialui/src/detail/Create.tsx
  packages/ra-ui-materialui/src/detail/CreateView.tsx
  packages/ra-ui-materialui/src/detail/Edit.tsx
  packages/ra-ui-materialui/src/detail/EditGuesser.tsx
  packages/ra-ui-materialui/src/detail/EditView.tsx
  packages/ra-ui-materialui/src/detail/Show.tsx
  packages/ra-ui-materialui/src/detail/ShowGuesser.tsx
  packages/ra-ui-materialui/src/detail/ShowView.tsx
  packages/ra-ui-materialui/src/list/List.tsx
  packages/ra-ui-materialui/src/list/ListGuesser.tsx
  packages/ra-ui-materialui/src/list/ListView.tsx
  packages/ra-ui-materialui/src/types.ts
Labels: RFR

#5538 Fix `<Admin history>` prop injection documentation misses package version constraint
  docs/Admin.md
Labels: RFR

#5543 [Doc] Improve List chapter screenshots and cross-links
  docs/List.md
  docs/Reference.md
  docs/img/list-view.jpg
  docs/img/list-view.png
  docs/img/simple-post-list.png
Labels: RFR

#5556 [Doc] Fix link formatting in "Writing your own input" documentation
  docs/Inputs.md
Labels: RFR

#5555 Fix variant and margin prop on an input have no effect inside a Filter form
  packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Labels: RFR

#5566 Fix missing Roboto font in e-commerce demo
  examples/demo/public/index.html
Labels: RFR

#5575 Move control of sidebar width to its menu child
  packages/ra-ui-materialui/src/layout/Menu.tsx
Labels: RFR

#5579 Fix ReferenceField doesn't accept the emptyText prop
  packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
Labels: RFR

#5583 Fix Edit Notifications are not shown
  examples/demo/package.json
  examples/simple/package.json
  examples/tutorial/package.json
  packages/ra-core/src/controller/details/useEditController.ts
  packages/ra-ui-materialui/package.json
  packages/react-admin/package.json
  yarn.lock
Labels: RFR

#5595 Export SimpleFormIteratorProps interface
  packages/ra-ui-materialui/src/form/index.tsx
Labels: RFR

#5594 Fix warning about deprecated prop in useCreateController
  packages/ra-core/src/controller/details/useCreateController.ts
Labels: RFR

#5597 [Doc] Fix create and edit controller usage documentation
  docs/CreateEdit.md
Labels: RFR

#5603 Fix optimized Datagrid freezes when using Expand
  examples/simple/src/posts/ResetViewsButton.js
  packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
Labels: RFR

#5598 Disable ripple effect
  examples/demo/src/layout/themes.ts
  packages/ra-ui-materialui/src/defaultTheme.ts
Labels: RFR

#5599 Fix data-generator avatars
  examples/data-generator/src/customers.ts
Labels: RFR

#5577 Fix logout causes error in useGetList
  packages/ra-core/src/dataProvider/useGetList.ts
  packages/ra-core/src/dataProvider/useQueryWithStore.ts
Labels: RFR
