Repository marmelab/react-admin, pull requests merged in 2020-01, with the labels that each got.

#4233 Fix withTranslate HOC uses defualt translate prop instead of the one from context
  packages/ra-core/src/i18n/translate.tsx
Labels: RFR

#4237 Fix graphql demo
  examples/demo/src/App.tsx
Labels: RFR

#4249 fix red validation message for SelectArrayInput
  packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
Labels: RFR

#4250 Sanitize translate props injected by the controller components inside views
  packages/ra-ui-materialui/src/detail/Create.js
  packages/ra-ui-materialui/src/detail/Edit.js
  packages/ra-ui-materialui/src/detail/Show.js
Labels: RFR

#4238 fix ra-data-graphql-simple convert SCALAR Date type to ISOString
  packages/ra-data-graphql-simple/src/buildVariables.js
Labels: RFR

#4261 Fix cache timeout reload list
  packages/ra-core/src/reducer/admin/resource/data.spec.ts
  packages/ra-core/src/reducer/admin/resource/data.ts
  packages/ra-core/src/reducer/admin/resource/list/ids.spec.ts
  packages/ra-core/src/reducer/admin/resource/list/ids.ts
Labels: RFR

#4239 Update empty admin image in doc
  docs/img/tutorial_empty.png
Labels: RFR

#4251 Ensure resource data in redux store is initialized bebfore using it.
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/controller/useListParams.ts
  packages/ra-core/src/controller/useRecordSelection.ts
Labels: RFR

#4274 Improve the documentation by setting the third-party library TinyMCE as deprecated in V3
  docs/Ecosystem.md
  docs/Inputs.md
Labels: RFR, documentation, v3

#4278 Improve the readability of the Input documentation
  docs/Inputs.md
Labels: RFR, documentation

#4285 Fix error in Confirm due to bad prop-types package version
  packages/ra-ui-materialui/package.json
  yarn.lock
Labels: RFR

#4291 Add explicit error in useDataProvider hook when the dataProvider throws a sync error
  docs/DataProviders.md
  packages/ra-core/src/dataProvider/useDataProvider.spec.js
  packages/ra-core/src/dataProvider/useDataProvider.ts
  packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
  packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
Labels: RFR

#4303 Fix NullableBooleanInput does not show initial value
  packages/ra-ui-materialui/src/input/NullableBooleanInput.spec.tsx
  packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
Labels: RFR

#4309 Add sticky header to Datagrid
  packages/ra-ui-materialui/src/list/Datagrid.js
  packages/ra-ui-materialui/src/list/List.js
Labels: RFR

#4315 Fix Menu overlapps the AppBar with material-ui > 4.8
  packages/ra-ui-materialui/src/layout/Sidebar.js
Labels: RFR

#4314 Remove the unused filter prop which in useGetMatchingReference
  packages/ra-core/src/controller/input/useGetMatchingReferences.ts
Labels: RFR

#4332 Fix <ImageInput> and <FileInput> doc and explain accept prop
  docs/Inputs.md
  docs/_layouts/default.html
  docs/css/style-v4.css
  docs/img/file-input.png
Labels: RFR

#4333 Fix missing basePath prop in Custom App doc
  docs/CustomApp.md
Labels: RFR

#4334 Fix outdated mention of aor-dependent-input in the FAQ
  docs/FAQ.md
Labels: RFR

#4335 Fix form customization code snippet in CreateEdit documentation
  docs/CreateEdit.md
Labels: RFR

#4336 Fix custom layout documentation doesn't mention the importance of the <Notification> component
  docs/Theming.md
Labels: RFR

#4341 Fix documentation about extending a dataProvider
  docs/DataProviders.md
Labels: RFR

#4339 Ensure useEditController specifies a default redirect to its caller
  packages/ra-core/src/controller/useEditController.ts
Labels: RFR

#4330 Fix upgrade documentation about form handling
  UPGRADE.md
Labels: RFR

#4347 Fix Default Value of Filters with Paths not Applied Correctly
  packages/ra-core/src/controller/useListParams.ts
Labels: RFR

#4338 Export Reference Utilities
  packages/ra-core/src/controller/input/index.ts
Labels: RFR

#4346 Fix Datagrid column headers don't update sort indicator when used in ReferenceManyField
  packages/ra-ui-materialui/src/list/DatagridHeaderCell.js
Labels: RFR

#4364 Fix Helper place on Inputs to avoid clipping/unclipping Forms
  cypress/integration/create.js
  examples/demo/src/ra-input-rich-text.d.ts
  packages/ra-input-rich-text/src/index.js
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
  packages/ra-ui-materialui/src/input/BooleanInput.tsx
  packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
  packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
  packages/ra-ui-materialui/src/input/DateInput.tsx
  packages/ra-ui-materialui/src/input/DateTimeInput.tsx
  packages/ra-ui-materialui/src/input/FileInput.tsx
  packages/ra-ui-materialui/src/input/InputHelperText.spec.tsx
  packages/ra-ui-materialui/src/input/InputHelperText.tsx
  packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
  packages/ra-ui-materialui/src/input/NumberInput.tsx
  packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
  packages/ra-ui-materialui/src/input/TextInput.tsx
Labels: RFR

#4373 Fix typo in Create / Edit documentation
  docs/CreateEdit.md
Labels: RFR

#4365 Add displayNull option in NullableBooleanInput and document it
  docs/Inputs.md
  docs/img/nullable-boolean-input-null-label.png
  packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
Labels: RFR

#4342 Reduce the default app weight by removing the image background on the Login screen
  docs/Theming.md
  packages/ra-ui-materialui/src/auth/Login.tsx
Labels: RFR

#4367 Fix Autocomplete selection display with custom Component
  docs/Inputs.md
  examples/simple/src/comments/CommentEdit.js
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR
