Repository marmelab/react-admin, pull requests merged in 2020-08, with the labels that each got.

#5097 Fix bulk delete confirmation dialog does not close after success when using Datagrid in a non-list page
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
Labels: RFR, bug

#4538 Add scroll buttons to tabs when they go beyond the available space
  cypress/plugins/index.js
  cypress/support/CreatePage.js
  cypress/support/EditPage.js
  docs/CreateEdit.md
  docs/Show.md
  packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
  packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.js
  packages/ra-ui-materialui/src/form/TabbedForm.js
  packages/ra-ui-materialui/src/form/TabbedForm.spec.js
  packages/ra-ui-materialui/src/form/TabbedFormTabs.js
Labels: RFR

#5111 Full height Layout & Sidebar margins
  packages/ra-ui-materialui/src/layout/Layout.js
  packages/ra-ui-materialui/src/layout/Menu.tsx
  packages/ra-ui-materialui/src/layout/Sidebar.js
Labels: RFR

#5113 Fix ra-input-rich-text dark theme compatibility
  packages/ra-input-rich-text/package-lock.json
  packages/ra-input-rich-text/package.json
  packages/ra-input-rich-text/src/styles.ts
Labels: RFR

#5110 Prevent crash when passing an undefined record to the <DeleteButton>
  docs/Reference.md
  packages/ra-ui-materialui/src/button/DeleteButton.tsx
Labels: RFR, bug

#5119 Fix missing styles for full height sidebar
  packages/ra-ui-materialui/src/layout/Sidebar.js
Labels: RFR

#5120 Fix some typos in the public website
  assets/styles.css
  index.html
Labels: RFR, documentation

#5125 Fix TypeError when suggested element in AutocompleteInput is empty
  packages/ra-core/src/form/useSuggestions.ts
Labels: RFR

#5124 Fix LogoutButton memorizes last visited page
  cypress/integration/create.js
  cypress/integration/tabs-with-routing.js
  packages/ra-core/src/auth/useLogout.ts
  packages/ra-ui-materialui/src/auth/Logout.tsx
Labels: RFR

#5094 Fix sorting a list using a <Datagrid> inside a <ReferenceManyField>
  cypress/support/ListPage.js
  packages/ra-ui-materialui/src/list/Datagrid.tsx
  packages/ra-ui-materialui/src/list/DatagridHeaderCell.js
  packages/ra-ui-materialui/src/list/DatagridHeaderCell.spec.js
Labels: RFR

#5077 Opt out sanitizeEmptyValues with SimpleForm and TabbedForm
  docs/CreateEdit.md
  packages/ra-core/src/form/FormWithRedirect.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.js
  packages/ra-ui-materialui/src/form/TabbedForm.js
Labels: RFR, enhancement

#5129 Fix ReferenceInput throws exception on custom pages
  packages/ra-core/src/controller/input/useGetMatchingReferences.ts
Labels: RFR

#5130 Fix bad type for useQuery options (onError -> onFailure)
  packages/ra-core/src/dataProvider/useQuery.ts
Labels: RFR

#5136 Fix warning about duplicate filter files with different case in esm build
  packages/ra-ui-materialui/src/list/filter/Filter.spec.js
  packages/ra-ui-materialui/src/list/filter/Filter.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.js
  packages/ra-ui-materialui/src/list/filter/FilterButton.spec.js
  packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.js
  packages/ra-ui-materialui/src/list/filter/FilterForm.js
  packages/ra-ui-materialui/src/list/filter/FilterForm.spec.js
  packages/ra-ui-materialui/src/list/filter/FilterFormInput.js
  packages/ra-ui-materialui/src/list/filter/index.ts
  packages/ra-ui-materialui/src/list/index.js
Labels: RFR

#5155 [Doc] Explain how to add a custom back button
  docs/CreateEdit.md
Labels: RFR

#5156 Fix imports
  packages/ra-core/src/form/FormWithRedirect.tsx
  packages/ra-core/src/reducer/admin/ui.ts
Labels: RFR

#5167 Fix clicking on the documentation link on small screens
  assets/styles.css
Labels: RFR

#5165 Allows List Empty Page Disabling
  docs/List.md
  packages/ra-ui-materialui/src/list/List.spec.js
  packages/ra-ui-materialui/src/list/ListView.tsx
  packages/ra-ui-materialui/src/types.ts
Labels: RFR

#5171 Fix a wrong documentation for the create verb in the simple REST Data Provider package
  packages/ra-data-simple-rest/README.md
Labels: RFR, documentation

#5172 Fixed documentation about `<NullableBooleanInput>`
  docs/Inputs.md
Labels: documentation

#5170 Convert Form components to typescript
  packages/ra-core/src/form/FormWithRedirect.tsx
  packages/ra-ui-materialui/src/form/FormInput.tsx
  packages/ra-ui-materialui/src/form/FormTab.spec.tsx
  packages/ra-ui-materialui/src/form/FormTab.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.tsx
  packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.tsx
  packages/ra-ui-materialui/src/form/TabbedFormTabs.spec.tsx
  packages/ra-ui-materialui/src/form/TabbedFormTabs.tsx
  packages/ra-ui-materialui/src/form/Toolbar.tsx
  packages/ra-ui-materialui/src/form/getFormInitialValues.ts
  packages/ra-ui-materialui/src/form/index.tsx
  packages/ra-ui-materialui/src/input/ArrayInput.tsx
Labels: RFR

#5175 Fix doc sidebar navigation on Firefox
  docs/_layouts/default.html
  docs/css/style-v5.css
Labels: RFR

#5176 Fix List subcontext lack resource data
  packages/ra-core/src/controller/ListFilterContext.tsx
  packages/ra-core/src/controller/ListPaginationContext.tsx
  packages/ra-core/src/controller/ListSortContext.tsx
  packages/ra-core/src/controller/useListFilterContext.ts
  packages/ra-core/src/controller/useListPaginationContext.ts
  packages/ra-core/src/controller/useListSortContext.ts
  packages/ra-ui-materialui/src/button/SortButton.tsx
Labels: RFR

#5180 Add user name and avatar on the top bar
  docs/Authentication.md
  docs/img/identity.png
  examples/demo/src/authProvider.ts
  examples/simple/src/authProvider.js
  packages/ra-core/src/auth/AuthContext.tsx
  packages/ra-core/src/auth/index.ts
  packages/ra-core/src/auth/useGetIdentity.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/layout/UserMenu.js
Labels: RFR

#5183 Migrate Layout components to typescript
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/input/NumberInput.tsx
  packages/ra-ui-materialui/src/input/ReferenceInput.tsx
  packages/ra-ui-materialui/src/layout/AppBar.tsx
  packages/ra-ui-materialui/src/layout/CardContentInner.tsx
  packages/ra-ui-materialui/src/layout/DeviceTestWrapper.tsx
  packages/ra-ui-materialui/src/layout/Error.tsx
  packages/ra-ui-materialui/src/layout/Layout.tsx
  packages/ra-ui-materialui/src/layout/LinearProgress.tsx
  packages/ra-ui-materialui/src/layout/Loading.tsx
  packages/ra-ui-materialui/src/layout/NotFound.tsx
  packages/ra-ui-materialui/src/layout/Responsive.spec.tsx
  packages/ra-ui-materialui/src/layout/Responsive.tsx
  packages/ra-ui-materialui/src/layout/Sidebar.tsx
  packages/ra-ui-materialui/src/layout/TitleForRecord.tsx
  packages/ra-ui-materialui/src/layout/TopToolbar.tsx
  packages/ra-ui-materialui/src/layout/UserMenu.tsx
  packages/ra-ui-materialui/src/layout/index.ts
Labels: RFR

#5187 Migrate remaining List components to TypeScript
  packages/ra-ui-materialui/src/defaultTheme.ts
  packages/ra-ui-materialui/src/detail/showFieldTypes.js
  packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
  packages/ra-ui-materialui/src/input/Labeled.tsx
  packages/ra-ui-materialui/src/list/List.spec.tsx
  packages/ra-ui-materialui/src/list/ListView.tsx
  packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridCell.spec.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridCell.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.spec.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridLoading.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
  packages/ra-ui-materialui/src/list/datagrid/ExpandRowButton.tsx
  packages/ra-ui-materialui/src/list/datagrid/index.ts
  packages/ra-ui-materialui/src/list/datagrid/useDatagridStyles.tsx
  packages/ra-ui-materialui/src/list/filter/Filter.spec.tsx
  packages/ra-ui-materialui/src/list/filter/Filter.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.js
  packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
  packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
  packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
  packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
  packages/ra-ui-materialui/src/list/index.js
  packages/ra-ui-materialui/src/list/index.ts
  packages/ra-ui-materialui/src/list/listFieldTypes.tsx
  packages/ra-ui-materialui/src/list/pagination/Pagination.spec.tsx
  packages/ra-ui-materialui/src/list/pagination/Pagination.tsx
  packages/ra-ui-materialui/src/list/pagination/PaginationActions.spec.tsx
  packages/ra-ui-materialui/src/list/pagination/PaginationActions.tsx
  packages/ra-ui-materialui/src/list/pagination/PaginationLimit.tsx
  packages/ra-ui-materialui/src/list/pagination/index.ts
Labels: RFR

#5193 Export More Types Related To useChoices
  packages/ra-core/src/form/index.ts
Labels: RFR

#5209 Fix useGetIdentity fails when there is no authProvider
  packages/ra-core/src/auth/useGetIdentity.ts
Labels: RFR

#5212 Fix Optimistic Effects Handling
  packages/ra-core/src/dataProvider/useDataProvider.ts
Labels: RFR
