Repository marmelab/react-admin, pull requests merged in 2021-02, with the labels that each got.

#5842 Fix SaveButton Breaking Change Regarding FormContext
  packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
  packages/ra-ui-materialui/src/button/SaveButton.tsx
Labels: RFR

#5848 Fix translatable inputs display
  packages/ra-core/src/controller/RecordContext.tsx
  packages/ra-ui-materialui/src/form/FormInput.tsx
  packages/ra-ui-materialui/src/input/TranslatableInputsTabContent.tsx
Labels: RFR

#5850 Fix Regression on ArrayInput children validation
  cypress/integration/edit.js
  cypress/support/EditPage.js
  examples/simple/src/posts/PostEdit.js
  packages/ra-core/src/form/useFormGroup.ts
  packages/ra-ui-materialui/src/form/FormTab.tsx
  packages/ra-ui-materialui/src/input/TranslatableInputsTab.tsx
Labels: RFR

#5851 [Doc] Fix onSuccess callback signature for optimistic and undoable queries
  docs/Actions.md
  docs/CreateEdit.md
Labels: RFR

#5852 Fix form.restart is not a function error
  packages/ra-ui-materialui/package.json
  packages/react-admin/package.json
  yarn.lock
Labels: RFR

#5859 Fix typo in docs
  docs/List.md
  examples/simple/src/tags/TagEdit.js
Labels: RFR

#5853 [TypeScript] Fix onSuccess / onFailure types
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
  packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
  packages/ra-core/src/controller/details/SaveContext.tsx
  packages/ra-core/src/controller/details/useCreateController.ts
  packages/ra-core/src/controller/details/useEditController.ts
  packages/ra-core/src/controller/saveModifiers.tsx
  packages/ra-core/src/dataProvider/performQuery/QueryFunctionParams.ts
  packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
  packages/ra-core/src/dataProvider/useDeclarativeSideEffects.ts
  packages/ra-core/src/dataProvider/useMutation.ts
  packages/ra-core/src/dataProvider/useQuery.ts
  packages/ra-core/src/dataProvider/useQueryWithStore.ts
  packages/ra-core/src/form/FormWithRedirect.tsx
  packages/ra-core/src/sideEffect/fetch.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/form/TabbedForm.tsx
  packages/ra-ui-materialui/src/types.ts
Labels: RFR

#5863 Fix error when using <List> outside of a ResourceContext
  packages/ra-core/src/controller/useListController.ts
Labels: RFR

#5876 Fix ArrayInput Always Override Inputs disabled Prop
  packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
Labels: RFR

#5877 Fix ReferenceManyField throws error after insert
  packages/ra-core/src/dataProvider/useGetManyReference.ts
Labels: RFR

#5875 [Doc] Fix links anchors
  CHANGELOG.md
  docs/Admin.md
  docs/CreateEdit.md
  docs/Ecosystem.md
  docs/List.md
  docs/Reference.md
  docs/Translation.md
  packages/ra-ui-materialui/src/layout/LinearProgress.tsx
Labels: RFR, documentation

#5900 Fix List view error after delete when using a field with no record test
  packages/ra-core/src/controller/useListController.spec.tsx
  packages/ra-core/src/controller/useListController.ts
  packages/ra-core/src/dataProvider/index.ts
  packages/ra-core/src/dataProvider/useGetMainList.tsx
  packages/ra-core/src/reducer/admin/resource/list/cachedRequests.ts
  packages/ra-core/src/reducer/admin/resource/list/ids.ts
Labels: RFR

#5884 Fix DeleteWithConfirmButton Does Not Allow to Override resource
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx
  packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/form/Toolbar.tsx
Labels: RFR

#5802 Fix warning when passing partial props to useListContext and other view context hooks
  examples/simple/src/customRouteLayout.js
  packages/ra-core/src/controller/details/useCreateContext.tsx
  packages/ra-core/src/controller/details/useEditContext.tsx
  packages/ra-core/src/controller/details/useShowContext.tsx
  packages/ra-core/src/controller/useListContext.ts
  packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Labels: WIP

#5911 Fix SaveButton Incorrectly Check FormContext Presence
  packages/ra-ui-materialui/src/button/SaveButton.tsx
Labels: RFR

#5903 Fix TabbedForm Does not Display Errors in Hidden Tabs on Submit
  packages/ra-ui-materialui/src/form/FormTab.tsx
  packages/ra-ui-materialui/src/form/FormTabHeader.tsx
  packages/ra-ui-materialui/src/form/index.tsx
Labels: RFR

#5905 Add scrollToTop on key navigation links
  docs/Buttons.md
  docs/img/bulk-delete-button.png
  docs/img/bulk-export-button.png
  docs/img/create-button-fab.png
  docs/img/create-button.png
  docs/img/edit-button.png
  docs/img/export-button.png
  docs/img/list-button.png
  docs/img/show-button.png
  docs/navigation.html
  packages/ra-core/src/controller/useListParams.spec.tsx
  packages/ra-core/src/controller/useListParams.ts
  packages/ra-core/src/core/CoreAdminRouter.tsx
  packages/ra-core/src/core/index.ts
  packages/ra-core/src/core/useScrollToTop.tsx
  packages/ra-core/src/dataProvider/useRefreshWhenVisible.ts
  packages/ra-core/src/sideEffect/useRedirect.ts
  packages/ra-ui-materialui/src/button/BulkDeleteButton.tsx
  packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
  packages/ra-ui-materialui/src/button/BulkExportButton.tsx
  packages/ra-ui-materialui/src/button/CreateButton.tsx
  packages/ra-ui-materialui/src/button/EditButton.tsx
  packages/ra-ui-materialui/src/button/ListButton.tsx
  packages/ra-ui-materialui/src/button/ShowButton.tsx
  packages/ra-ui-materialui/src/button/SkipNavigationButton.tsx
  packages/ra-ui-materialui/src/button/SortButton.tsx
  packages/ra-ui-materialui/src/layout/Menu.tsx
  packages/ra-ui-materialui/src/list/BulkActionsToolbar.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
Labels: RFR

#5922 Fix DataProvider Stacked Queries Resolution
  packages/ra-core/src/dataProvider/useDataProvider.ts
Labels: RFR

#5925 Restore Skiped Loading Tests
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
  packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
  packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
Labels: RFR

#5931 Fix useGetManyReference loading state detection
  packages/ra-core/src/controller/field/ReferenceManyFieldController.spec.tsx
  packages/ra-core/src/dataProvider/useGetManyReference.ts
Labels: RFR

#5895 Ensure form children can override props
  packages/ra-ui-materialui/src/form/FormInput.tsx
  packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
Labels: WIP

#5886 Add ListContext to ReferenceArrayInput
  docs/Inputs.md
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-core/src/controller/input/ReferenceArrayInputContext.ts
  packages/ra-core/src/controller/input/ReferenceArrayInputContextProvider.tsx
  packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
  packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx
  packages/ra-core/src/controller/input/index.ts
  packages/ra-core/src/controller/input/useReferenceArrayInputContext.ts
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-core/src/util/index.ts
  packages/ra-core/src/util/indexById.ts
  packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js
  packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
Labels: RFR

#5945 Tabbed components disable routing
  docs/CreateEdit.md
  docs/Show.md
  packages/ra-ui-materialui/src/detail/Tab.tsx
  packages/ra-ui-materialui/src/detail/TabbedShowLayout.spec.js
  packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx
  packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.tsx
  packages/ra-ui-materialui/src/detail/index.ts
  packages/ra-ui-materialui/src/form/FormTab.spec.tsx
  packages/ra-ui-materialui/src/form/FormTab.tsx
  packages/ra-ui-materialui/src/form/FormTabHeader.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.tsx
  packages/ra-ui-materialui/src/form/TabbedFormTabs.tsx
  packages/ra-ui-materialui/src/form/TabbedFormView.tsx
  packages/ra-ui-materialui/src/form/index.tsx
Labels: RFR

#5953 Fix CheckboxGroup error style when in ReferenceArrayInput
  packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
  packages/ra-ui-materialui/src/input/sanitizeInputRestProps.ts
Labels: RFR
