Repository marmelab/react-admin, pull requests merged in 2022-08, with the labels that each got.

#8026 [Documentation] Fix deep linking between versions
  docs/404.html
  docs/navigation.html
Labels: RFR

#8017 Add a "Clear all filters" button
  packages/ra-core/src/i18n/TranslationMessages.ts
  packages/ra-language-english/src/index.ts
  packages/ra-language-french/src/index.ts
  packages/ra-ui-materialui/src/list/List.stories.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx
  packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
  packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
Labels: RFR

#8035 Fix: Update CategoryList to use RecodContext
  examples/demo/src/categories/CategoryList.tsx
Labels: RFR

#8036 Feat: Add filter redirection for pending reviews
  examples/demo/src/dashboard/CardWithIcon.tsx
  examples/demo/src/dashboard/PendingReviews.tsx
Labels: RFR

#8031 [Fix] Add localStorage application key
  docs/Store.md
  packages/ra-core/src/store/localStorageStore.spec.tsx
  packages/ra-core/src/store/localStorageStore.ts
Labels: RFR

#8029 Fix ArrayInput Adding Previously Removed Item
  packages/ra-ui-materialui/src/input/ArrayInput/AddItemButton.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Labels: RFR

#8023 Fix delete contexts don't send mutation `meta`
  docs/Buttons.md
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.spec.tsx
  packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
  packages/ra-core/src/controller/button/useDeleteWithUndoController.spec.tsx
  packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
  packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
  packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
Labels: WIP

#8040 [TypeScript] Fix MenuItemLink prop type isn't exported
  packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
Labels: RFR

#8039 Add ability to remove empty option in SelectInput for required fields
  packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
  packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
  packages/ra-ui-materialui/src/input/SelectInput.tsx
Labels: RFR

#8037 Fix AutocompleteInput suggestions flicker when used inside ReferenceInput
  docs/AutocompleteInput.md
  docs/SelectInput.md
  packages/ra-core/src/controller/input/useReferenceInputController.ts
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR

#8048 [Doc] Document how to sanitize form values
  docs/Create.md
  docs/Edit.md
  docs/Inputs.md
Labels: RFR

#8052 Fix use custom preview component for FileInput and ImageInput
  packages/ra-ui-materialui/src/input/FileInput.tsx
  packages/ra-ui-materialui/src/input/FileInputPreview.tsx
Labels: RFR

#8055 [Fix] Validation errors don't show on `Edit` page
  packages/ra-core/src/controller/input/useReferenceInputController.spec.tsx
  packages/ra-core/src/form/useIsFormInvalid.ts
Labels: RFR

#8056 [Doc] Add JsonSchemaForm doc
  docs/JsonSchemaForm.md
  docs/navigation.html
Labels: RFR

#8057 Fix Display notification on each submit if form has errors
  packages/ra-core/src/form/index.ts
  packages/ra-core/src/form/useAugmentedForm.ts
  packages/ra-core/src/form/useNotifyIsFormInvalid.ts
Labels: RFR

#8045 [Doc] Improve ImageField, NumberField and SelectField docs
  docs/ImageField.md
  docs/NumberField.md
  docs/SelectField.md
  docs/img/number-field.webp
Labels: RFR

#8058 Fix useStore internal state reset when key changes
  packages/ra-core/src/store/useStore.spec.tsx
  packages/ra-core/src/store/useStore.ts
Labels: RFR

#8061 Fix FormDataConsumer inside SimpleFormIterator adds empty value
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Labels: RFR

#8065 [Doc] Add useGetTree doc
  docs/navigation.html
  docs/useGetTree.md
Labels: RFR

#8066 Fix remove useless `RaFileInput-preview` and `RaImageInput-preview` classnames
  docs/FileInput.md
  docs/ImageInput.md
  packages/ra-ui-materialui/src/input/FileInput.tsx
  packages/ra-ui-materialui/src/input/ImageInput.tsx
Labels: RFR

#8068 [Doc] Add `label` prop for `<ReferenceInput>` and `<ReferenceArrayInput>` in docs
  docs/ReferenceArrayInput.md
  docs/ReferenceInput.md
  docs/Upgrade.md
Labels: RFR

#8071 [TypeScript] Add `resettable` prop to `SelectInputProps`
  packages/ra-ui-materialui/src/input/SelectInput.tsx
Labels: RFR

#8078 Fix: `multiLine` prop is not working in `Notification`
  packages/ra-ui-materialui/src/layout/Notification.tsx
Labels: RFR

#8088 Fix `<CoreAdmin store>` prop is ignored
  packages/ra-core/src/core/CoreAdmin.tsx
Labels: RFR

#8089 [Doc] Fix upgrade guide still mentioning TextInput transform pop
  docs/Inputs.md
Labels: RFR

#8080 Fix <ArrayInput> validation does not prevent submission
  cypress/integration/create.js
  examples/simple/package.json
  packages/ra-core/package.json
  packages/ra-input-rich-text/package.json
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
  packages/react-admin/package.json
  yarn.lock
Labels: RFR, DNM

#8067 Add support for SimpleFormIterator inline and sx props
  docs/ArrayInput.md
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIteratorStyles.ts
Labels: RFR

#8090 Fix ArrayInput doesn't support scalar values
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Labels: RFR

#7917 Add components to show only time
  docs/DateField.md
  docs/TimeInput.md
  docs/img/time-input-edge.gif
  docs/img/time-input-firefox.gif
  docs/navigation.html
  packages/ra-ui-materialui/src/field/DateField.spec.tsx
  packages/ra-ui-materialui/src/field/DateField.tsx
  packages/ra-ui-materialui/src/input/TimeInput.spec.tsx
  packages/ra-ui-materialui/src/input/TimeInput.stories.tsx
  packages/ra-ui-materialui/src/input/TimeInput.tsx
  packages/ra-ui-materialui/src/input/index.ts
Labels: RFR

#8103 Feat: Add useGetRecordId in ra-core
  packages/ra-core/src/dataProvider/useGetRecordId.spec.tsx
  packages/ra-core/src/dataProvider/useGetRecordId.ts
Labels: RFR

#8104 Fix guesser for of ReferenceField and ReferenceArrayField
  packages/ra-core/src/inference/InferredElement.ts
  packages/ra-core/src/inference/inferElementFromValues.spec.tsx
  packages/ra-core/src/inference/inferElementFromValues.tsx
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/input/index.ts
  packages/ra-ui-materialui/src/list/ListGuesser.stories.tsx
  packages/ra-ui-materialui/src/list/listFieldTypes.tsx
Labels: RFR

#8102 Fix `useGetList`'s `onSuccess` side effect overriding internal one
  packages/ra-core/src/dataProvider/useGetList.spec.tsx
  packages/ra-core/src/dataProvider/useGetList.ts
Labels: RFR

#8109 Feat: Update TabbedForm documentation
  docs/TabbedForm.md
Labels: documentation, RFR

#8106 Feat: Update documentation JsonSchemaForm
  docs/JsonSchemaForm.md
Labels: RFR

#8117 [doc] Fix ReferenceArrayField doc to use a child-less syntax first
  docs/ReferenceArrayField.md
Labels: RFR

#8063 Add useInfiniteGetList hook
  docs/img/useInfiniteGetList.gif
  docs/navigation.html
  docs/useInfiniteGetList.md
  packages/ra-core/src/dataProvider/index.ts
  packages/ra-core/src/dataProvider/useInfiniteGetList.spec.tsx
  packages/ra-core/src/dataProvider/useInfiniteGetList.stories.tsx
  packages/ra-core/src/dataProvider/useInfiniteGetList.ts
  packages/ra-core/src/storybook/data.ts
  packages/ra-core/src/types.ts
Labels: RFR

#8107 Feat: add useGetRecordId documentation
  docs/navigation.html
  docs/useGetRecordId.md
Labels: RFR

#8122 Fix code error in *Usage* example of ra-data-localstorage README
  packages/ra-data-localstorage/README.md
Labels: RFR

#8120 [Doc] Add ReferenceManyInput chapter
  docs/ArrayInput.md
  docs/Reference.md
  docs/ReferenceManyField.md
  docs/ReferenceManyInput.md
  docs/SimpleFormIterator.md
  docs/img/array-input.gif
  docs/img/reference-many-input.gif
  docs/img/simple-form-iterator-inline.png
  docs/navigation.html
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Labels: RFR

#8127 Doc: Fix rbac links
  docs/canAccess.md
  docs/useCanAccess.md
  docs/usePermissions.md
Labels: RFR
