Repository marmelab/react-admin, pull requests merged in 2023-01, with the labels that each got.

#8538 [Doc] Better explain custom error page limitations
  docs/Theming.md
Labels: RFR

#8541 Add ability to set `anchorOrigin` in `useNotify`
  docs/img/notification.webp
  docs/useNotify.md
  packages/ra-core/src/notification/types.ts
  packages/ra-ui-materialui/src/layout/Notification.stories.tsx
  packages/ra-ui-materialui/src/layout/Notification.tsx
Labels: RFR

#8542 Add data sharing across tabs in `ra-data-local-storage`
  packages/ra-data-localstorage/README.md
  packages/ra-data-localstorage/src/index.ts
Labels: RFR

#8547 [Doc] Fix `<ContainerLayout>` is hard to find.
  docs/Admin.md
  docs/ContainerLayout.md
  docs/Layout.md
Labels: RFR

#8461 [Doc] Show nav sidebar on main navigation page
  docs/_layouts/default.html
  docs/css/style-v13.css
  docs/documentation.html
  docs/js/ra-doc-exec.js
  docs/navigation.html
Labels: WIP

#8546 Fix `ListGuesser` links to Edit view even though there is only a ShowView
  packages/ra-ui-materialui/src/list/ListGuesser.stories.tsx
  packages/ra-ui-materialui/src/list/ListGuesser.tsx
  packages/ra-ui-materialui/src/list/listFieldTypes.tsx
Labels: RFR

#8543 Add ability to pass a tab count in `<TabbedForm.Tab>` and `<TabbedShowLayout.Tab>`
  docs/TabbedForm.md
  docs/TabbedShowLayout.md
  examples/demo/src/orders/OrderList.tsx
  examples/demo/src/products/ProductEdit.tsx
  examples/simple/src/posts/PostEdit.tsx
  examples/simple/src/posts/PostShow.tsx
  packages/ra-ui-materialui/src/detail/Tab.tsx
  packages/ra-ui-materialui/src/detail/TabbedShowLayout.stories.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx
  packages/ra-ui-materialui/src/form/FormTab.tsx
  packages/ra-ui-materialui/src/form/FormTabHeader.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.stories.tsx
Labels: RFR

#8551 Allow to extend the authProvider
  packages/ra-core/src/auth/useAuthProvider.ts
Labels: RFR

#8553 [no ci] [Doc] Better explain how to build a `parse` fn with `DateTimeInput`
  docs/DateTimeInput.md
Labels: RFR

#8555 [Doc] Add Realtime documentation
  docs/DataProviderLive.md
  docs/DataProviders.md
  docs/Edit.md
  docs/EditLive.md
  docs/List.md
  docs/ListLive.md
  docs/Menu.md
  docs/MenuLive.md
  docs/Realtime.md
  docs/RealtimeDataProvider.md
  docs/Reference.md
  docs/Show.md
  docs/ShowLive.md
  docs/css/style-v13.css
  docs/documentation.html
  docs/img/CollaborativeDemo.mp4
  docs/img/EditLive.png
  docs/img/ListLive.png
  docs/img/MenuLive.png
  docs/img/RealtimeMenu.png
  docs/img/ShowLive.png
  docs/img/locks-demo.gif
  docs/img/useLockOnCall.gif
  docs/img/useLockOnMount.gif
  docs/img/useSubscribe.gif
  docs/img/useSubscribeCallback.gif
  docs/img/useSubscribeOnce.gif
  docs/img/useSubscribeOnceCallback.gif
  docs/img/useSubscribeToRecord.gif
  docs/img/useSubscribeToRecordList.gif
  docs/img/useSubscribeUnsubscribe.gif
  docs/navigation.html
  docs/useGetList.md
  docs/useGetListLive.md
  docs/useGetLock.md
  docs/useGetLockLive.md
  docs/useGetLocks.md
  docs/useGetLocksLive.md
  docs/useGetOne.md
  docs/useGetOneLive.md
  docs/useLock.md
  docs/useLockOnCall.md
  docs/useLockOnMount.md
  docs/usePublish.md
  docs/useSubscribe.md
  docs/useSubscribeCallback.md
  docs/useSubscribeToRecord.md
  docs/useSubscribeToRecordList.md
  docs/useUnlock.md
Labels: RFR

#8556 Fix `AutocompleteInput` with `create` does not support nested `optionText` and fix `enableGetChoices` examples in doc
  docs/ReferenceArrayInput.md
  docs/ReferenceInput.md
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR

#8557 [Doc] Make custom headers example compatible with TS
  docs/DataProviders.md
Labels: documentation, RFR

#8563 [Doc] Revert custom headers example (#8557) and add another for TS
  docs/DataProviders.md
Labels: documentation, RFR

#8565 [Doc] Add `disableAuthentication` prop description on <Show> component
  docs/Show.md
Labels: RFR

#8558 Add new authProviders (auth0, cognito)
  docs/AuthProviderList.md
Labels: RFR

#8526 Memoize mutation callbacks
  packages/ra-core/src/dataProvider/useCreate.ts
  packages/ra-core/src/dataProvider/useDelete.ts
  packages/ra-core/src/dataProvider/useDeleteMany.ts
  packages/ra-core/src/dataProvider/useUpdate.ts
  packages/ra-core/src/dataProvider/useUpdateMany.ts
  packages/ra-core/src/store/useStore.ts
  packages/ra-core/src/util/index.ts
  packages/ra-core/src/util/useEvent.spec.tsx
  packages/ra-core/src/util/useEvent.ts
Labels: RFR

#8568 [Doc] Fix code examples
  docs/ReferenceManyCount.md
  docs/ReferenceManyInput.md
  docs/useGetLock.md
  docs/useInfiniteGetList.md
Labels: RFR

#8580 Add ability to use a React Node as `useNotify` message
  docs/img/use-notify-node.png
  docs/useNotify.md
  packages/ra-core/src/notification/types.ts
  packages/ra-core/src/notification/useNotify.ts
  packages/ra-ui-materialui/src/layout/Notification.stories.tsx
  packages/ra-ui-materialui/src/layout/Notification.tsx
Labels: RFR

#8583 [Doc] Add HelpDesk demo
  docs/Demos.md
Labels: RFR

#8588 [doc] Add illustration to list and edit tutorials
  docs/EditTutorial.md
  docs/ListTutorial.md
  docs/img/edit-from-react-to-react-admin.webp
  docs/img/list-from-react-to-react-admin.webp
Labels: RFR

#8599 Fix AutocompleteInput flickers inside ReferenceInput
  packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Labels: RFR

#8601 Make SelectArrayInput more resilient
  packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
Labels: RFR

#8598 [Doc] Add Features chapter
  docs/AppBar.md
  docs/Authentication.md
  docs/DataProviderIntroduction.md
  docs/Features.md
  docs/FilteringTutorial.md
  docs/Realtime.md
  docs/Store.md
  docs/Tutorial.md
  docs/documentation.html
  docs/img/CRUD.webm
  docs/img/accessibility.webp
  docs/img/dense.webp
  docs/img/reference-field-link.png
  docs/img/reference-input-filter.webm
  docs/img/responsive.webm
  docs/img/typescript.webm
  docs/navigation.html
  packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
Labels: RFR

#8602 Fix AutocompleteInput when multiple is true and value is not an array
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR

#8603 Fix useGetManyAggregate ids is not an array
  packages/ra-core/src/dataProvider/useGetManyAggregate.ts
Labels: RFR

#8610 Fix NumberInput should support entering a decimal number with a transitory invalid value
  packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
  packages/ra-ui-materialui/src/input/NumberInput.tsx
Labels: RFR

#8608 Fix AutocompleteArrayInput when value is not an array
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR

#8614 Fix useless useEffect in demo
  examples/crm/src/dashboard/DealsChart.tsx
  packages/ra-ui-materialui/src/field/ArrayField.tsx
Labels: RFR
