Repository marmelab/react-admin, pull requests merged in 2023-06, with the labels that each got.

#8964 [TypeScript] Fix regression in type of `<FunctionField>` `render`
  packages/ra-ui-materialui/src/field/FunctionField.stories.tsx
  packages/ra-ui-materialui/src/field/FunctionField.tsx
Labels: RFR

#8965 [Doc] Add Next.js app router install instructions
  docs/NextJs.md
  docs/img/nextjs-file-structure-app-router.png
  docs/img/nextjs-react-admin.webp
  packages/ra-core/src/core/CoreAdminContext.tsx
  packages/ra-core/src/core/CoreAdminRoutes.tsx
  packages/ra-ui-materialui/src/AdminUI.tsx
  packages/react-admin/src/Admin.tsx
Labels: RFR

#8967 [Doc] Fix missing styles and JS for older 4.x versions
  doc/4.0/css/docsearch.css
  doc/4.0/js/materialize.min.js
  doc/4.0/js/prism.js
  doc/4.0/js/ra-doc-exec.js
  doc/4.1/css/docsearch.css
  doc/4.1/js/materialize.min.js
  doc/4.1/js/prism.js
  doc/4.1/js/ra-doc-exec.js
  doc/4.10/js/materialize.min.js
  doc/4.10/js/prism.js
  doc/4.10/js/ra-doc-exec.js
  doc/4.11/js/materialize.min.js
  doc/4.11/js/prism.js
  doc/4.11/js/ra-doc-exec.js
  doc/4.2/css/docsearch.css
  doc/4.2/js/materialize.min.js
  doc/4.2/js/prism.js
  doc/4.2/js/ra-doc-exec.js
  doc/4.3/css/docsearch.css
  doc/4.3/js/materialize.min.js
  doc/4.3/js/prism.js
  doc/4.3/js/ra-doc-exec.js
  doc/4.4/css/docsearch.css
  doc/4.4/js/materialize.min.js
  doc/4.4/js/prism.js
  doc/4.4/js/ra-doc-exec.js
  doc/4.5/css/docsearch.css
  doc/4.5/js/materialize.min.js
  doc/4.5/js/prism.js
  doc/4.5/js/ra-doc-exec.js
  doc/4.6/js/materialize.min.js
  doc/4.6/js/prism.js
  doc/4.6/js/ra-doc-exec.js
  doc/4.7/css/docsearch.css
  doc/4.7/js/materialize.min.js
  doc/4.7/js/prism.js
  doc/4.7/js/ra-doc-exec.js
  doc/4.8/css/docsearch.css
  doc/4.8/js/materialize.min.js
  doc/4.8/js/prism.js
  doc/4.8/js/ra-doc-exec.js
  doc/4.9/js/materialize.min.js
  doc/4.9/js/prism.js
  doc/4.9/js/ra-doc-exec.js
Labels: RFR

#8974 [Doc] Add documentation for `<TreeInput>` and `<ReferenceNodeInput>`
  docs/Features.md
  docs/Inputs.md
  docs/Reference.md
  docs/ReferenceInput.md
  docs/ReferenceNodeInput.md
  docs/SelectInput.md
  docs/TreeInput.md
  docs/TreeWithDetails.md
  docs/img/ReferenceNodeInput-TreeInput-basic.mp4
  docs/img/ReferenceNodeInput-TreeInput-basic.webm
  docs/img/ReferenceNodeInput-TreeInput-multiple.mp4
  docs/img/ReferenceNodeInput-TreeInput-multiple.webm
  docs/navigation.html
Labels: RFR

#8969 [Doc] Add `<AutoSave>` documentation
  docs/AccordionForm.md
  docs/AutoSave.md
  docs/EditTutorial.md
  docs/Features.md
  docs/Form.md
  docs/LongForm.md
  docs/Reference.md
  docs/SimpleForm.md
  docs/TabbedForm.md
  docs/Validation.md
  docs/WizardForm.md
  docs/img/AutoSave.mp4
  docs/img/AutoSave.webm
  docs/img/validation.png
  docs/navigation.html
Labels: RFR

#8976 Fix `<ReferenceField>` line height isn't consistent with other fields
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
Labels: RFR

#8979 [Doc] Better explain the type of `getSource` and `scopedFormData` in `<FormDataConsumer>`
  docs/Inputs.md
  docs/SimpleFormIterator.md
Labels: RFR

#8980 Fix configurable does not have a targetable root class
  packages/ra-ui-materialui/src/preferences/Configurable.tsx
Labels: RFR

#8977 Update `<Link>` to honor the `underline` prop
  packages/ra-ui-materialui/src/Link.tsx
Labels: RFR

#8985 [Doc] Fix Confirm prop table overflows
  docs/Confirm.md
Labels: RFR

#8984 [Doc] Fix links to react-hook-form's doc
  docs/AccordionForm.md
  docs/ArrayInput.md
  docs/Features.md
  docs/Form.md
  docs/Inputs.md
  docs/LongForm.md
  docs/SimpleForm.md
  docs/SimpleFormIterator.md
  docs/TabbedForm.md
  docs/Upgrade.md
  docs/Validation.md
  docs/WizardForm.md
  docs/useInput.md
  docs/useRecordContext.md
  packages/ra-core/src/form/Form.tsx
  packages/ra-core/src/form/useFormValues.ts
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInputContext.ts
  packages/ra-ui-materialui/src/input/ArrayInput/useArrayInput.ts
  packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Labels: RFR

#8989 [Doc] Fix `<ReferenceArrayInput>` section about custom query filter
  docs/ReferenceArrayInput.md
Labels: RFR

#8990 Fix `<Admin>` fails when used in Next.js server components
  docs/NextJs.md
  packages/react-admin/src/Admin.tsx
Labels: RFR

#8991 [Doc] Fix broken link in Realtime documentation
  docs/Realtime.md
Labels: RFR

#8993 Fix `<WithRecord>` `render` prop type
  examples/demo/src/orders/NbItemsField.tsx
  packages/ra-core/src/controller/record/WithRecord.tsx
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/field/FunctionField.tsx
Labels: RFR

#8994 [JSDoc] Fix ToggleThemeButton deprecated props JSDoc
  packages/ra-ui-materialui/src/button/ToggleThemeButton.tsx
Labels: RFR

#8995 Fix ListView does not apply CSS classes to its child components
  packages/ra-ui-materialui/src/list/ListView.tsx
Labels: RFR, fix

#8997 Update ra-input-rich-text tiptap dependencies
  packages/ra-input-rich-text/package.json
  packages/ra-input-rich-text/src/RichTextInput.spec.tsx
  yarn.lock
Labels: RFR

#8998 Doc: update React links
  docs/AppBar.md
  docs/AutocompleteArrayInput.md
  docs/AutocompleteInput.md
  docs/CustomRoutes.md
  docs/Layout.md
  docs/RichTextField.md
  docs/SelectInput.md
  docs/Theming.md
  docs/Title.md
  docs/Upgrade.md
  docs/useStore.md
Labels: RFR

#9001 Fix: query permissions at startup only when a child function exist
  packages/create-react-admin/templates/local-auth-provider/authProvider.ts
  packages/ra-core/src/auth/usePermissions.ts
Labels: RFR

#9006 [Doc] Use WebM and MP4 videos instead of GIF for EE components
  docs/AccordionForm.md
  docs/AppBar.md
  docs/Breadcrumb.md
  docs/Buttons.md
  docs/Calendar.md
  docs/Create.md
  docs/CreateDialog.md
  docs/CreateInDialogButton.md
  docs/Datagrid.md
  docs/DualListInput.md
  docs/Edit.md
  docs/EditDialog.md
  docs/EditInDialogButton.md
  docs/EditTutorial.md
  docs/EditableDatagrid.md
  docs/Features.md
  docs/FilteringTutorial.md
  docs/IconMenu.md
  docs/Layout.md
  docs/Menu.md
  docs/MultiLevelMenu.md
  docs/Resource.md
  docs/Search.md
  docs/ShowInDialogButton.md
  docs/Theming.md
  docs/WizardForm.md
  docs/useGetTree.md
Labels: RFR

#9010 Revert "Fix `<Admin>` fails when used in Next.js server components"
  docs/NextJs.md
  packages/react-admin/src/Admin.tsx
Labels: RFR

#9011 Fix broken link in Next installation tutorial
  docs/NextJs.md
Labels: RFR

#9012 [Doc] Fix Next.js pages router installation misses src directory
  docs/NextJs.md
  docs/img/nextjs-file-structure.png
Labels: RFR

#8971 fix(array-input): update form state w/ default values
  packages/ra-core/src/form/useApplyInputDefaultValues.ts
  packages/ra-core/src/form/useInput.ts
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
Labels: RFR

#9014 Fix nextjs integration
  docs/NextJs.md
  packages/ra-core/src/index.ts
  packages/ra-data-fakerest/src/index.ts
  packages/ra-data-graphql-simple/src/index.ts
  packages/ra-data-graphql/src/index.ts
  packages/ra-data-json-server/src/index.ts
  packages/ra-data-localforage/src/index.ts
  packages/ra-data-localstorage/src/index.ts
  packages/ra-data-simple-rest/src/index.ts
  packages/ra-i18n-polyglot/src/index.ts
  packages/ra-input-rich-text/src/index.ts
  packages/ra-language-english/src/index.ts
  packages/ra-language-french/src/index.ts
  packages/ra-no-code/src/index.ts
  packages/ra-ui-materialui/src/index.ts
  packages/react-admin/src/index.ts
Labels: RFR

#9016 [Doc] Add PredictiveTextInput chapter
  docs/Features.md
  docs/Inputs.md
  docs/PredictiveTextInput.md
  docs/TextInput.md
  docs/img/PredictiveTextInput-multiline.png
  docs/img/PredictiveTextInput.mp4
  docs/navigation.html
Labels: RFR

#9017 Add documentation for Remix v2routing conventions
  docs/Remix.md
Labels: RFR

#9015 Add references the documentation about linking two inputs
  docs/Create.md
  docs/Edit.md
  docs/Form.md
  docs/SimpleForm.md
  docs/TabbedForm.md
Labels: RFR

#9005 Automatically convert TS examples to JS
  docs/_layouts/default.html
  docs/css/prism.css
  docs/css/style-v17.css
  docs/js/ra-doc-exec.js
  docs/useDataProvider.md
Labels: RFR

#9020 Partially revert "Fix Next.js integration"
  docs/NextJs.md
Labels: RFR

#9019 Allow disabling store persistence of the list parameters
  docs/List.md
  docs/useListController.md
  packages/ra-core/src/controller/list/useInfiniteListController.ts
  packages/ra-core/src/controller/list/useListController.storeKey.spec.tsx
  packages/ra-core/src/controller/list/useListController.storeKey.stories.tsx
  packages/ra-core/src/controller/list/useListController.ts
  packages/ra-core/src/controller/list/useListParams.ts
  packages/ra-ui-materialui/src/list/List.stories.tsx
Labels: RFR

#9022 Update DataProvider File Upload Documentation To Leverage withLifeCycleCallbacks
  docs/DataProviders.md
Labels: RFR

#8999 Add unique validator
  cypress/e2e/create.cy.js
  cypress/support/CreatePage.js
  docs/Reference.md
  docs/Validation.md
  docs/img/useUnique.mp4
  docs/img/useUnique.webm
  docs/navigation.html
  docs/useUnique.md
  examples/simple/src/users/UserCreate.tsx
  packages/ra-core/src/form/index.ts
  packages/ra-core/src/form/useUnique.spec.tsx
  packages/ra-core/src/form/useUnique.stories.tsx
  packages/ra-core/src/form/useUnique.ts
  packages/ra-core/src/util/asyncDebounce.spec.ts
  packages/ra-core/src/util/asyncDebounce.ts
  packages/ra-core/src/util/index.ts
  packages/ra-language-english/src/index.ts
  packages/ra-language-french/src/index.ts
Labels: RFR

#9018 Fix RichTextInput toolbar appearance
  docs/RichTextInput.md
  docs/img/rich-text-input.mp4
  docs/img/rich-text-input.webm
  examples/simple/src/posts/PostEdit.tsx
  packages/ra-input-rich-text/src/RichTextInput.stories.tsx
  packages/ra-input-rich-text/src/RichTextInput.tsx
  packages/ra-input-rich-text/src/RichTextInputToolbar.tsx
  packages/ra-input-rich-text/src/buttons/ColorButtons.tsx
  packages/ra-input-rich-text/src/buttons/ImageButtons.tsx
  packages/ra-input-rich-text/src/buttons/LevelSelect.tsx
Labels: RFR

#9024 Fix linter warnings
  packages/ra-core/src/controller/edit/EditBase.spec.tsx
  packages/ra-core/src/form/validate.spec.ts
  packages/ra-data-graphql-simple/src/getResponseParser.ts
  packages/ra-ui-materialui/src/auth/Logout.tsx
  packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
  packages/ra-ui-materialui/src/detail/CreateActions.tsx
  packages/ra-ui-materialui/src/detail/CreateView.tsx
  packages/ra-ui-materialui/src/detail/EditActions.tsx
  packages/ra-ui-materialui/src/detail/EditView.tsx
  packages/ra-ui-materialui/src/detail/Show.stories.tsx
  packages/ra-ui-materialui/src/detail/ShowView.tsx
  packages/ra-ui-materialui/src/detail/editFieldTypes.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
  packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
  packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Labels: RFR

#9027 [DOC] - Fix typo on useGetTree documentation
  docs/useGetTree.md
Labels: RFR

#9033 Fix linter warnings
  examples/simple/src/users/UserEdit.tsx
  examples/simple/src/users/UserList.tsx
  packages/ra-core/src/auth/useCheckAuth.spec.tsx
  packages/ra-core/src/auth/useLogin.spec.tsx
  packages/ra-core/src/controller/create/CreateBase.spec.tsx
  packages/ra-core/src/controller/create/useCreateController.spec.tsx
  packages/ra-core/src/controller/edit/useEditController.spec.tsx
  packages/ra-core/src/controller/input/useReferenceArrayInputController.spec.tsx
  packages/ra-core/src/controller/list/useInfiniteListController.spec.tsx
  packages/ra-core/src/controller/list/useListController.spec.tsx
  packages/ra-core/src/controller/saveContext/useSaveContext.ts
  packages/ra-core/src/core/CustomRoutes.tsx
  packages/ra-core/src/dataProvider/useGetList.spec.tsx
  packages/ra-core/src/dataProvider/useGetMany.spec.tsx
  packages/ra-core/src/dataProvider/useGetManyAggregate.spec.tsx
  packages/ra-core/src/dataProvider/useGetOne.spec.tsx
  packages/ra-core/src/dataProvider/useInfiniteGetList.stories.tsx
  packages/ra-core/src/dataProvider/withLifecycleCallbacks.spec.ts
  packages/ra-core/src/form/getFormInitialValues.spec.ts
  packages/ra-core/src/form/useAugmentedForm.ts
  packages/ra-no-code/src/ui/NewResourceMenuItem.tsx
  packages/ra-no-code/src/ui/ResourceMenuItem.tsx
  packages/ra-no-code/src/ui/useImportResourceFromCsv.tsx
  packages/ra-ui-materialui/src/Labeled.tsx
  packages/ra-ui-materialui/src/Link.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR

#9037 Prevent render InputHelperText if helperText props is false in Input components
  packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
  packages/ra-ui-materialui/src/input/BooleanInput.tsx
  packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
  packages/ra-ui-materialui/src/input/DateInput.tsx
  packages/ra-ui-materialui/src/input/DateTimeInput.tsx
  packages/ra-ui-materialui/src/input/FileInput.tsx
  packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
  packages/ra-ui-materialui/src/input/NumberInput.tsx
  packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
  packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
  packages/ra-ui-materialui/src/input/SelectInput.tsx
  packages/ra-ui-materialui/src/input/TextInput.tsx
  packages/ra-ui-materialui/src/input/TimeInput.tsx
Labels: RFR

#9040 [Doc] Correct an example in useList doc, with page option
  docs/useList.md
Labels: documentation, RFR

#9030 [Doc] Improve description of rbac tab, panel, section, and step
  docs/AuthRBAC.md
Labels: documentation, RFR

#9041 [Doc] Fix a typo: missing e to the
  docs/TabbedForm.md
Labels: documentation, RFR

#8937 Upgrade to TS 5
  .eslintrc
  cypress/start.js
  examples/crm/package.json
  examples/data-generator/package.json
  examples/demo/package.json
  examples/no-code/package.json
  examples/simple/package.json
  examples/tutorial/package.json
  jest.config.js
  package.json
  packages/create-react-admin/package.json
  packages/ra-core/package.json
  packages/ra-core/src/core/Resource.tsx
  packages/ra-data-fakerest/package.json
  packages/ra-data-graphql-simple/package.json
  packages/ra-data-graphql/package.json
  packages/ra-data-json-server/package.json
  packages/ra-data-localforage/package.json
  packages/ra-data-localstorage/package.json
  packages/ra-data-simple-rest/package.json
  packages/ra-i18n-polyglot/package.json
  packages/ra-input-rich-text/package.json
  packages/ra-language-english/package.json
  packages/ra-language-french/package.json
  packages/ra-no-code/package.json
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/form/FormTabHeader.tsx
  packages/ra-ui-materialui/src/input/SelectInput.tsx
  packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
  packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
  packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
  packages/react-admin/package.json
  yarn.lock
Labels: RFR

#9045 [Doc] - Correct Controlled Mode explanation in TabbedShowLayout
  docs/TabbedShowLayout.md
Labels: documentation, RFR

#9049 [Doc] - fix a typo: "a books fields" instead of "an books fields"
  docs/FieldsForRelationships.md
Labels: RFR

#9047 Fix demos don't allow to visualize source maps
  examples/crm/package.json
  examples/crm/vite.config.ts
  examples/demo/package.json
  examples/demo/vite.config.ts
  yarn.lock
Labels: RFR

#9053 [Doc] fix a typo in ReferenceOneField documentation
  docs/ReferenceOneField.md
Labels: RFR

#9056 Fix: string value supplied to BooleanInput checked prop
  packages/ra-ui-materialui/src/input/BooleanInput.tsx
Labels: RFR

#9052 [Doc] Add SmartRichTextInput, an AI assistant for rich text content
  docs/Features.md
  docs/Inputs.md
  docs/PredictiveTextInput.md
  docs/Reference.md
  docs/RichTextInput.md
  docs/SmartRichTextInput.md
  docs/TextInput.md
  docs/navigation.html
Labels: RFR

#9058 Remove use client
  packages/ra-core/src/index.ts
  packages/ra-data-fakerest/src/index.ts
  packages/ra-data-graphql-simple/src/index.ts
  packages/ra-data-graphql/src/index.ts
  packages/ra-data-json-server/src/index.ts
  packages/ra-data-localforage/src/index.ts
  packages/ra-data-localstorage/src/index.ts
  packages/ra-data-simple-rest/src/index.ts
  packages/ra-i18n-polyglot/src/index.ts
  packages/ra-input-rich-text/src/index.ts
  packages/ra-language-english/src/index.ts
  packages/ra-language-french/src/index.ts
  packages/ra-no-code/src/index.ts
  packages/ra-ui-materialui/src/index.ts
  packages/react-admin/src/index.ts
Labels: RFR
