Repository marmelab/react-admin, pull requests merged in 2023-05, with the labels that each got.

#8886 [Doc] Fix wrong parameter `to` for `Menu.ResourceItem`
  docs/CustomRoutes.md
Labels: RFR

#8882 Fix custom redirect in pessimistic `Edit` or `Create` when using `warnWhenUnsavedChanges` (new approach)
  packages/ra-core/src/controller/create/useCreateController.spec.tsx
  packages/ra-core/src/controller/edit/useEditController.spec.tsx
  packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
Labels: RFR, fix

#8881 Update tutorial to use create-react-admin
  docs/CreateReactAdmin.md
  docs/Tutorial.md
  docs/img/create-react-admin.webm
  docs/navigation.html
Labels: documentation, RFR

#8874 Add ability to default to dark mode when users prefer it
  docs/Admin.md
  docs/AppBar.md
  docs/AuthProviderList.md
  docs/Theming.md
  docs/ToggleThemeButton.md
  docs/img/AppBar-children.png
  docs/img/dark-theme.png
  docs/img/not-found.png
  examples/demo/src/App.tsx
  examples/demo/src/authProvider.ts
  examples/demo/src/configuration/Configuration.tsx
  examples/demo/src/layout/AppBar.tsx
  packages/ra-input-rich-text/src/buttons/ColorButtons.tsx
  packages/ra-ui-materialui/src/AdminContext.spec.tsx
  packages/ra-ui-materialui/src/AdminContext.tsx
  packages/ra-ui-materialui/src/button/Button.stories.tsx
  packages/ra-ui-materialui/src/button/ToggleThemeButton.spec.tsx
  packages/ra-ui-materialui/src/button/ToggleThemeButton.stories.tsx
  packages/ra-ui-materialui/src/button/ToggleThemeButton.tsx
  packages/ra-ui-materialui/src/button/ToggleThemeLegacyButton.tsx
  packages/ra-ui-materialui/src/defaultTheme.ts
  packages/ra-ui-materialui/src/layout/AppBar.stories.tsx
  packages/ra-ui-materialui/src/layout/AppBar.tsx
  packages/ra-ui-materialui/src/layout/Menu.stories.tsx
  packages/ra-ui-materialui/src/layout/Theme/ThemeProvider.spec.tsx
  packages/ra-ui-materialui/src/layout/Theme/ThemeProvider.tsx
  packages/ra-ui-materialui/src/layout/Theme/ThemesContext.ts
  packages/ra-ui-materialui/src/layout/Theme/index.ts
  packages/ra-ui-materialui/src/layout/Theme/types.ts
  packages/ra-ui-materialui/src/layout/Theme/useTheme.spec.tsx
  packages/ra-ui-materialui/src/layout/Theme/useTheme.ts
  packages/ra-ui-materialui/src/layout/Theme/useThemesContext.ts
  packages/ra-ui-materialui/src/layout/ThemeTestWrapper.tsx
  packages/ra-ui-materialui/src/list/filter/SavedQueriesList.stories.tsx
  packages/react-admin/src/Admin.tsx
Labels: RFR

#8896 [Doc] fix import statements in example code
  docs/Count.md
  docs/FilteringTutorial.md
Labels: documentation

#8898 [Doc] Allow TOC sidebar to scroll vertically
  docs/_layouts/default.html
  docs/css/style-v16.css
  docs/documentation.html
Labels: RFR

#8899 Fix ReferenceField link function is called with referencing record
  packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
Labels: RFR

#8902 Fix create-react-admin requires node 16
  packages/create-react-admin/package.json
  packages/create-react-admin/templates/common/vite.config.ts
Labels: RFR

#8862 Update RaRecord type & fix some other types
  examples/demo/src/dashboard/PendingReviews.tsx
  examples/demo/src/reviews/ReviewItem.tsx
  packages/ra-core/src/controller/record/useRecordContext.ts
  packages/ra-core/src/dataProvider/useGetMany.ts
  packages/ra-core/src/dataProvider/useGetRecordId.ts
  packages/ra-core/src/routing/types.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/src/field/FunctionField.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
Labels: RFR, TypeScript

#8906 [Doc] Add Advanced Tutorial about Custom Tags Selector
  docs/AdvancedTutorials.md
Labels: RFR

#8905 Add `purifyOptions` prop to `<RichTextField>`
  docs/RichTextField.md
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/field/RichTextField.stories.tsx
  packages/ra-ui-materialui/src/field/RichTextField.tsx
  yarn.lock
Labels: RFR

#8908 Bump RHF version and simplify `useInput` validation
  examples/simple/package.json
  packages/ra-core/package.json
  packages/ra-core/src/form/useInput.ts
  packages/ra-input-rich-text/package.json
  packages/ra-ui-materialui/package.json
  packages/react-admin/package.json
  yarn.lock
Labels: RFR

#8912 Fix ReferenceFieldView backward compatibility
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
Labels: RFR

#8915 Fix `SimpleForm` and `TabbedForm` do not sanitize the `resetOptions` prop
  packages/ra-ui-materialui/src/form/SimpleForm.tsx
  packages/ra-ui-materialui/src/form/TabbedForm.tsx
Labels: RFR

#8917 Add WithListContext component
  docs/ArrayField.md
  docs/ListBase.md
  docs/ListTutorial.md
  docs/Reference.md
  docs/ReferenceArrayField.md
  docs/ReferenceManyField.md
  docs/SingleFieldList.md
  docs/WithListContext.md
  docs/WithRecord.md
  docs/img/ReferenceArrayField-default-child.png
  docs/img/WithListContext-chart.png
  docs/navigation.html
  docs/useListContext.md
  docs/useRecordContext.md
  examples/demo/src/dashboard/CardWithIcon.tsx
  examples/demo/src/dashboard/NewCustomers.tsx
  packages/ra-core/package.json
  packages/ra-core/src/controller/list/WithListContext.stories.tsx
  packages/ra-core/src/controller/list/WithListContext.tsx
  packages/ra-core/src/controller/list/index.ts
  yarn.lock
Labels: RFR

#8920 Fix `<SaveButton>` spinner while submitting
  packages/ra-ui-materialui/src/button/SaveButton.stories.tsx
  packages/ra-ui-materialui/src/button/SaveButton.tsx
Labels: RFR

#8916 Typescript documentation
  docs/WithRecord.md
  docs/css/prism.css
  docs/js/prism.js
  docs/useAuthProvider.md
  docs/useCreate.md
  docs/useDataProvider.md
  docs/useDelete.md
  docs/useDeleteMany.md
  docs/useEditContext.md
  docs/useGetList.md
  docs/useGetListLive.md
  docs/useGetMany.md
  docs/useGetManyReference.md
  docs/useGetOne.md
  docs/useGetOneLive.md
  docs/useListContext.md
  docs/useRecordContext.md
  docs/useShowContext.md
  docs/useUpdate.md
  docs/useUpdateMany.md
Labels: RFR

#8933 Fix create and edit controller's `save` callback should use calltime `meta` param
  packages/ra-core/src/controller/create/useCreateController.spec.tsx
  packages/ra-core/src/controller/create/useCreateController.ts
  packages/ra-core/src/controller/edit/useEditController.spec.tsx
  packages/ra-core/src/controller/edit/useEditController.ts
Labels: RFR

#8935 Fix create-react-admin adds unnecessary files
  packages/create-react-admin/src/generateProject.ts
Labels: RFR

#8934 [Doc] Fix tutorial with create-react-admin
  docs/Tutorial.md
  docs/css/prism.css
Labels: RFR

#8923 Fix Create generic record type
  packages/ra-core/src/controller/create/CreateBase.tsx
  packages/ra-core/src/controller/create/useCreateController.ts
  packages/ra-core/src/dataProvider/useCreate.ts
  packages/ra-core/src/types.ts
  packages/ra-data-localforage/src/index.ts
  packages/ra-data-localstorage/src/index.ts
  packages/ra-ui-materialui/src/detail/Create.tsx
  packages/ra-ui-materialui/src/types.ts
Labels: RFR, TypeScript

#8863 Add TS support to fields
  docs/Fields.md
  docs/js/prism.js
  examples/crm/src/companies/LogoField.tsx
  examples/crm/src/contacts/TagsListEdit.tsx
  examples/crm/src/dataGenerator/types.ts
  examples/crm/src/types.ts
  examples/demo/src/products/ProductReferenceField.tsx
  examples/demo/src/reviews/ReviewItem.tsx
  examples/demo/src/types.ts
  examples/demo/src/visitors/FullNameField.tsx
  packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
  packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
  packages/ra-core/src/controller/list/useRecordSelection.ts
  packages/ra-core/src/controller/record/useRecordContext.ts
  packages/ra-core/src/controller/useReference.ts
  packages/ra-core/src/dataProvider/useCreate.ts
  packages/ra-core/src/dataProvider/useGetMany.ts
  packages/ra-core/src/types.ts
  packages/ra-ui-materialui/package.json
  packages/ra-ui-materialui/src/detail/EditGuesser.tsx
  packages/ra-ui-materialui/src/field/ArrayField.tsx
  packages/ra-ui-materialui/src/field/BooleanField.stories.tsx
  packages/ra-ui-materialui/src/field/BooleanField.tsx
  packages/ra-ui-materialui/src/field/ChipField.tsx
  packages/ra-ui-materialui/src/field/DateField.tsx
  packages/ra-ui-materialui/src/field/EmailField.tsx
  packages/ra-ui-materialui/src/field/FileField.tsx
  packages/ra-ui-materialui/src/field/FunctionField.tsx
  packages/ra-ui-materialui/src/field/ImageField.tsx
  packages/ra-ui-materialui/src/field/NumberField.tsx
  packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
  packages/ra-ui-materialui/src/field/ReferenceField.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
  packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
  packages/ra-ui-materialui/src/field/RichTextField.tsx
  packages/ra-ui-materialui/src/field/SelectField.tsx
  packages/ra-ui-materialui/src/field/TextField.tsx
  packages/ra-ui-materialui/src/field/UrlField.tsx
  packages/ra-ui-materialui/src/field/WrapperField.tsx
  packages/ra-ui-materialui/src/field/genericMemo.ts
  packages/ra-ui-materialui/src/field/index.ts
  packages/ra-ui-materialui/src/field/types.ts
  packages/ra-ui-materialui/src/types.ts
  yarn.lock
Labels: RFR, TypeScript

#8914 Expose setNotifications methods in notification contexts
  packages/ra-core/src/notification/NotificationContext.ts
  packages/ra-core/src/notification/NotificationContextProvider.tsx
Labels: enhancement

#8939 Fix ra-language-french package.json to avoid including tsconfig
  packages/ra-language-french/package.json
Labels: RFR

#8941 Fix `useGetList` default `onSuccess` throws when the query is disabled
  packages/ra-core/src/dataProvider/useGetList.spec.tsx
  packages/ra-core/src/dataProvider/useGetList.ts
Labels: RFR

#8938 [Doc] Fix NextJS tutorial for the latest version of create-next-app
  docs/NextJs.md
  docs/img/nextjs-setup.webp
Labels: RFR

#8956 Fix `<AutocompleteInput>` should not use `matchSuggestion` when in a `<ReferenceInput>`
  packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
  packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Labels: RFR
