Repository marmelab/react-admin, pull requests merged in 2024-08, with the labels that each got.

#10117 Fix(crm): Improvement for UI + fix processCompanyLogo
  examples/crm/src/contacts/ContactList.tsx
  examples/crm/src/contacts/ContactListContent.tsx
  examples/crm/src/dashboard/DashboardActivityLog.tsx
  examples/crm/src/dashboard/DealsChart.tsx
  examples/crm/src/dashboard/HotContacts.tsx
  examples/crm/src/dashboard/TasksList.tsx
  examples/crm/src/dashboard/TasksListFilter.tsx
  examples/crm/src/dashboard/Welcome.tsx
  examples/crm/src/dataProvider.ts
  examples/crm/src/deals/DealShow.tsx
  examples/crm/src/misc/ImageEditorField.tsx
  examples/crm/src/tasks/AddTask.tsx
Labels: RFR, CRM

#10055 [DNM] [Doc] Remove v5 annoucement banner
  docs/_layouts/default.html
  docs/documentation.html
Labels: RFR

#10067 [Doc] Remove all RA v5 teasing banners
  _layouts/default.html
  doc/5.0/documentation.html
  documentation.html
  index.html
  landing-page/index.html
Labels: RFR

#10114 Fix setSort ignores the sort order when the chosen field is the current one
  packages/ra-core/src/controller/list/queryReducer.spec.ts
  packages/ra-core/src/controller/list/queryReducer.ts
Labels: RFR

#10113 Feat(crm): Keep company tab when changing page
  examples/crm/src/companies/CompanyShow.tsx
Labels: RFR, CRM

#10118 Feat(crm): Supabase look alike upload file
  examples/crm/src/authProvider.ts
  examples/crm/src/companies/CompanyInputs.tsx
  examples/crm/src/contacts/Avatar.tsx
  examples/crm/src/dataGenerator/contacts.ts
  examples/crm/src/dataGenerator/sales.ts
  examples/crm/src/dataProvider.ts
  examples/crm/src/misc/ImageEditorField.tsx
  examples/crm/src/notes/NoteAttachments.tsx
  examples/crm/src/types.ts
Labels: RFR, CRM

#10119 Fix(crm): Improve import speed via batching, add estimated remaining time
  examples/crm/src/contacts/ContactAside.tsx
  examples/crm/src/contacts/ContactImportButton.tsx
  examples/crm/src/contacts/ContactImportModal.tsx
  examples/crm/src/contacts/contacts_export.csv
  examples/crm/src/contacts/useContactImport.tsx
  examples/crm/src/misc/usePapaParse.tsx
Labels: RFR, CRM

#10123 Feat(crm): Add possibility to disable Sale
  examples/crm/src/companies/CompanyInputs.tsx
  examples/crm/src/contacts/ContactInputs.tsx
  examples/crm/src/dataProvider.ts
  examples/crm/src/notes/NoteCreate.tsx
  examples/crm/src/sales/SalesEdit.tsx
  examples/crm/src/sales/SalesInputs.tsx
  examples/crm/src/sales/SalesList.tsx
  examples/crm/src/types.ts
Labels: RFR, CRM

#10124 Feat(crm): Code modified to look more like Atomic Crm
  examples/crm/src/activity/ActivityLogNote.tsx
  examples/crm/src/dataGenerator/contactNotes.ts
  examples/crm/src/dataGenerator/contacts.ts
  examples/crm/src/dataGenerator/dealNotes.ts
  examples/crm/src/dataGenerator/deals.ts
  examples/crm/src/dataProvider.ts
  examples/crm/src/deals/DealEmpty.tsx
  examples/crm/src/deals/DealList.tsx
  examples/crm/src/types.ts
Labels: RFR, CRM

#10131 Update and fix create-react-admin
  packages/create-react-admin/src/generateAppTestFile.ts
  packages/create-react-admin/templates/common/.eslintrc.cjs
  packages/create-react-admin/templates/common/.eslintrc.js
  packages/create-react-admin/templates/common/package.json
  packages/create-react-admin/templates/common/prettier.config.js
  packages/create-react-admin/templates/common/tsconfig.app.json
  packages/create-react-admin/templates/common/tsconfig.json
  packages/create-react-admin/templates/common/tsconfig.node.json
  packages/create-react-admin/templates/common/vite.config.ts
  packages/create-react-admin/templates/ra-data-fakerest/package.json
  packages/create-react-admin/templates/ra-data-fakerest/src/dataProvider.ts
  packages/create-react-admin/templates/ra-data-fakerest/tsconfig.app.json
  packages/create-react-admin/templates/ra-data-fakerest/tsconfig.json
  packages/create-react-admin/templates/ra-data-fakerest/vite.config.ts
Labels: RFR

#10132 Add `<ReferenceManyField storeKey>` to allow more than one reference for the same resource
  packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
  packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
  packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
  packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
Labels: RFR

#10134 [Doc] Fix ReferenceInput usage
  docs/Inputs.md
Labels: RFR

#10135 [Doc] Update ra-search documentation to mention disableHighlight
  docs/Search.md
  docs/SearchWithResult.md
Labels: documentation, RFR

#10142 [Doc] Document `<ReferenceManyField storeKey>` prop
  docs/ReferenceManyField.md
Labels: RFR

#10143 [Doc] Remove more references to ra-enterprise webm videos
  docs/AccordionForm.md
  docs/DatagridAG.md
  docs/EditableDatagrid.md
  docs/StackedFilters.md
Labels: RFR

#10144 Fix `<PrevNextButtons>` index when using paginated results
  packages/ra-core/src/controller/usePrevNextController.ts
  packages/ra-ui-materialui/src/button/PrevNextButtons.spec.tsx
Labels: RFR

#10150 [Doc] Improve types in QuickFilter doc
  docs/FilteringTutorial.md
Labels: RFR

#10148 Fix: `useInput` should call a custom validator with the final source in respect to the `<SourceContext>`
  packages/ra-core/src/form/useInput.spec.tsx
  packages/ra-core/src/form/useInput.ts
Labels: RFR

#10137 [Doc] Add screencast for EditInDialogButton in ReferenceManyField documentation
  docs/ReferenceManyField.md
Labels: RFR

#10159 [Doc] Features and Filtering Tutorial: Fix links to video assets
  docs/Features.md
  docs/FilteringTutorial.md
Labels: RFR

#10169 expand expect with testing-library helper for all tests
  test-setup.js
Labels: RFR

#10164 Add global Reset CSS
  docs/Remix.md
  docs/Vite.md
  examples/crm/index.html
  examples/demo/index.html
  examples/no-code/index.html
  examples/simple/index.html
  examples/tutorial/src/index.css
  examples/tutorial/src/main.tsx
  packages/create-react-admin/templates/common/index.html
  packages/ra-ui-materialui/src/AdminUI.tsx
  packages/ra-ui-materialui/src/button/ToggleThemeButton.spec.tsx
Labels: RFR

#10163 Fix input validation and dirty state after re-enabling disabled fields
  examples/simple/package.json
  packages/ra-core/package.json
  packages/ra-core/src/form/useFormGroup.ts
  packages/ra-core/src/form/useInput.spec.tsx
  packages/ra-core/src/form/useInput.ts
  packages/ra-input-rich-text/package.json
  packages/ra-ui-materialui/package.json
  packages/react-admin/package.json
  yarn.lock
Labels: RFR
